SUDA NAVEEN - 20MIC0057
suda.naveen2020@vitstudent.ac.in

Git Hub Folder link: https://github.com/sudanaveen4/SmartBridge---VIT-EXTERNSHIP-Artificial-Intelligence-.git

ASSESMENT:-1

In [16]:
import pandas as pd
import numpy as np

In [17]:
# Task 1: Create a pandas dataframe with numpy random values
data = np.random.rand(4, 4)
print(data)
df = pd.DataFrame(data, columns=['Feature 1', 'Feature 2', 'Feature 3', 'Feature 4'])
print(df)

[[0.54671028 0.18485446 0.96958463 0.77513282]
 [0.93949894 0.89482735 0.59789998 0.92187424]
 [0.0884925  0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751 0.35675333]]
   Feature 1  Feature 2  Feature 3  Feature 4
0   0.546710   0.184854   0.969585   0.775133
1   0.939499   0.894827   0.597900   0.921874
2   0.088493   0.195983   0.045227   0.325330
3   0.388677   0.271349   0.828738   0.356753


In [18]:
# Task 2: Rename the column names
# Rename the column names
df.columns = ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']
df

Random value 1  Random value 2  Random value 3  Random value 4
0        0.546710        0.184854        0.969585        0.775133
1        0.939499        0.894827        0.597900        0.921874
2        0.088493        0.195983        0.045227        0.325330
3        0.388677        0.271349        0.828738        0.356753

In [19]:
# Task 3: Descriptive statistics of the dataframe
descriptive_stats = df.describe()
print(descriptive_stats)

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.490845        0.386753        0.610362        0.594773
std          0.354371        0.340888        0.406719        0.299320
min          0.088493        0.184854        0.045227        0.325330
25%          0.313631        0.193201        0.459732        0.348898
50%          0.467694        0.233666        0.713319        0.565943
75%          0.644907        0.427219        0.863949        0.811818
max          0.939499        0.894827        0.969585        0.921874


In [20]:
# Task 4: Check for null values and data types
# Check for null values
null_values = df.isnull().sum()
print("Null Values:\n", null_values)

# Find data type of columns
column_data_types = df.dtypes
print("Data Types:\n", column_data_types)

Null Values:
 Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64
Data Types:
 Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object


In [21]:
# Task 5: Display 'Random value 2' & 'Random value 3' columns
random_value_2 = df['Random value 2']
random_value_3 = df['Random value 3']
print("\nRandom Value 2:\n", random_value_2)
print("\nRandom Value 3:\n", random_value_3)

# Display with location method
random_value_2_loc = df.loc[:, 'Random value 2']
random_value_3_loc = df.loc[:, 'Random value 3']
print("\nRandom Value 2 (Location method):\n", random_value_2_loc)
print("\nRandom Value 3 (Location method):\n", random_value_3_loc)

# Display with index location method
random_value_2_idx = df.iloc[:, 1]
random_value_3_idx = df.iloc[:, 2]
print("\nRandom Value 2 (Index location method):\n", random_value_2_idx)
print("\nRandom Value 3 (Index location method):\n", random_value_3_idx)


Random Value 2:
 0    0.184854
1    0.894827
2    0.195983
3    0.271349
Name: Random value 2, dtype: float64

Random Value 3:
 0    0.969585
1    0.597900
2    0.045227
3    0.828738
Name: Random value 3, dtype: float64

Random Value 2 (Location method):
 0    0.184854
1    0.894827
2    0.195983
3    0.271349
Name: Random value 2, dtype: float64

Random Value 3 (Location method):
 0    0.969585
1    0.597900
2    0.045227
3    0.828738
Name: Random value 3, dtype: float64

Random Value 2 (Index location method):
 0    0.184854
1    0.894827
2    0.195983
3    0.271349
Name: Random value 2, dtype: float64

Random Value 3 (Index location method):
 0    0.969585
1    0.597900
2    0.045227
3    0.828738
Name: Random value 3, dtype: float64
